package ru.nsu.p2p.common.protocol.core;

public enum MessageType {
    TRACKER_REGISTER_REQ,
    TRACKER_REGISTER_RES,
    TRACKER_HEARTBEAT_REQ,
    TRACKER_PUBLISH_REQ,
    TRACKER_CATALOG_REQ,
    TRACKER_CATALOG_RES,
    TRACKER_GET_PEERS_REQ,
    TRACKER_GET_PEERS_RES,
    TRACKER_ERROR_RES,

    PEER_HANDSHAKE,
    PEER_BITFIELD,
    PEER_CHUNK_REQ,
    PEER_CHUNK_PAYLOAD

}
